name: "Feature Request"
description: "Suggest an idea or improvement for the project"
title: "[Feature]: "
type: "Feature"
labels: ["wish list"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please provide detailed information to help us understand and evaluate your idea.

  - type: input
    id: summary
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the feature or enhancement."
      placeholder: "e.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "What problem does this feature solve?"
      description: "Explain the problem or limitation this feature would address."
      placeholder: "e.g., It's difficult to use the app in low-light environments."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe how you think this feature should work."
      placeholder: "e.g., Add a toggle in settings to switch between light and dark mode."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered other solutions or workarounds?"
      placeholder: "e.g., Using browser extensions to force dark mode."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, or examples to explain your request."
      placeholder: "e.g., A screenshot of a similar feature in another project."
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: "Checklist"
      description: "Please confirm the following:"
      options:
        - label: "I have searched existing issues to ensure this feature hasn't been requested before."
          required: true
        - label: "I understand that feature requests are not guaranteed to be implemented."
          required: true
